export const initializeSiteRequirement = [
  { name: "Living Room", height: null, breadth: null, length: null, uploads:[] },
  { name: "Bedroom", height: null, breadth: null, length: null, uploads:[] },
  { name: "Kitchen", height: null, breadth: null, length: null, uploads:[] },
  { name: "Dining Room", height: null, breadth: null, length: null, uploads:[] },
  { name: "Balcony", height: null, breadth: null, length: null, uploads:[] },
  { name: "Foyer Area", height: null, breadth: null, length: null, uploads:[] },
  { name: "Terrace", height: null, breadth: null, length: null, uploads:[] },
  { name: "Study Room", height: null, breadth: null, length: null, uploads:[] },
  { name: "Car Parking", height: null, breadth: null, length: null, uploads:[] },
  { name: "Garden", height: null, breadth: null, length: null, uploads:[] },
  { name: "Storage Room", height: null, breadth: null, length: null, uploads:[] },
  { name: "Entertainment Room", height: null, breadth: null, length: null, uploads:[] },
  { name: "Home Gym", height: null, breadth: null, length: null, uploads:[] },
];
